### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by tillkruss** [DisplaceTech/dgxpco#3]
We're installing WordPress using Composer:

```json
{
  "require": {
    "johnpbloch/wordpress-core": "^4.8.0",
    "johnpbloch/wordpress-core-installer": "~1.0"
  }
}
```

Are there any plans to support checking signatures of this as well?

**Comment by ericmann** [comment]
Not at this time. Composer downloads are significantly different than core ZIP downloads. I'll follow up with @johnpbloch and see if there's a way we _could_ add support, but at the moment that's not on the roadmap.

That being said, [Composer itself is looking to add support for this kind of functionality in the future](https://github.com/composer/composer/issues/4022).
